<?php

namespace Database\Seeders;

use App\Models\Scheme;
use Illuminate\Database\Seeder;

class MetadataSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'code' => 'AS-1',
                'division' => 'North Lakhimpur',
                'name' => 'R/S to Kakoi R/B embankment from Lilabari T.G. to Kadam including breach closing work with A/E measures.',
                'estimated_lakh' => 299.93,
                'status' => 'Foreclosed / Ongoing',
                'progress' => 60.00,
                'util_cs' => 269.94, 'util_ss' => 30.00, 'util_tot' => 299.94,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-2',
                'division' => 'Nagaon',
                'name' => 'R/S to Hatimura dyke from Kukurakata Hill to Hatimura Hill (0 M to 3595 M).',
                'estimated_lakh' => 337.40,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 303.61, 'util_ss' => 33.79, 'util_tot' => 337.40,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-3',
                'division' => 'Mangaldoi',
                'name' => 'R/S of Saktola embankment (B/B) from MPK Road to R.K. Embankment (Ch. 0 to 6.6 Km B/B).',
                'estimated_lakh' => 326.51,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 293.85, 'util_ss' => 32.66, 'util_tot' => 326.51,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-4',
                'division' => 'Nalbari',
                'name' => 'Protection of Sahpur, Durgamandir and its adjoining area from the erosion / sloughening action of river Buradia on both banks at different reaches.',
                'estimated_lakh' => 396.15,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 356.54, 'util_ss' => 39.62, 'util_tot' => 396.16,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-5',
                'division' => 'Silchar',
                'name' => 'R/S to dyke along L/B of Sonai from SM road to Dharmikhal L/B Sonai (Ch. 9900 to 12400 M).',
                'estimated_lakh' => 180.26,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 162.23, 'util_ss' => 17.66, 'util_tot' => 179.89,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-6',
                'division' => 'Silchar Mech',
                'name' => 'Removal of drainage congestion with machinery and equipments of Rangirkhari channel, Malugram area and Silchar town.',
                'estimated_lakh' => 243.00,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 50.65, 'util_ss' => 24.30, 'util_tot' => 74.95,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-7',
                'division' => 'Dhemaji',
                'name' => 'R/S of B/dyke from Dirmore to Sonarigaon 7th km to 14th km.',
                'estimated_lakh' => 739.43,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 639.98, 'util_ss' => 73.94, 'util_tot' => 713.92,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-9',
                'division' => 'Sivasagar',
                'name' => 'R/S to B/dyke from Laibeel to Rajabari including A/E measures at Teteliguri area.',
                'estimated_lakh' => 542.38,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 484.50, 'util_ss' => 54.25, 'util_tot' => 538.75,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-10',
                'division' => 'Nagaon',
                'name' => 'R/S to flood embankment along R/B of Kolong river from Phulaguri to Mulankata and Raha to Chaparmukh including A/E measures.',
                'estimated_lakh' => 603.10,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 521.07, 'util_ss' => 66.99, 'util_tot' => 588.06,
                'req_cs' => 16.48, 'req_ss' => 0.00, 'req_tot' => 16.48,
            ],
            [
                'code' => 'AS-11',
                'division' => 'Nagaon',
                'name' => 'R/S to B/T dyke along L/B of Kopilli from Charaibhagi to Tuklaitup from Ch. 20600M to 27400M.',
                'estimated_lakh' => 734.40,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 635.65, 'util_ss' => 76.61, 'util_tot' => 712.26,
                'req_cs' => 12.64, 'req_ss' => 0.00, 'req_tot' => 12.64,
            ],
            [
                'code' => 'AS-12',
                'division' => 'Nagaon',
                'name' => 'R/S to closing of Kopilli spill channel from Kharikhana to Jugijan (4700 M to 23000 M).',
                'estimated_lakh' => 743.41,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 643.38, 'util_ss' => 79.52, 'util_tot' => 722.90,
                'req_cs' => 20.51, 'req_ss' => 0.00, 'req_tot' => 20.51,
            ],
            [
                'code' => 'AS-13',
                'division' => 'Guwahati East',
                'name' => 'R/S to F/E along L/B Kollong from Baghjan to Bagibari ch 17th km to 28th km. Ph-II.',
                'estimated_lakh' => 608.28,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 547.44, 'util_ss' => 60.84, 'util_tot' => 608.28,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-14',
                'division' => 'Nalbari',
                'name' => 'R/S to R/B embankment of Borolia river from Somurkhat to Dusutimukh from ch 9.50Km to 19.60 Km.',
                'estimated_lakh' => 620.00,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 558.00, 'util_ss' => 59.92, 'util_tot' => 617.92,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-15',
                'division' => 'Kokrajhar',
                'name' => 'Improvement, strengthening and training of river Sankosh at Daimamari.',
                'estimated_lakh' => 670.73,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 603.64, 'util_ss' => 67.09, 'util_tot' => 670.73,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-16',
                'division' => 'Silchar',
                'name' => 'A/E measures at Karatigram under Silchar town from the erosion of river Barak on its R/B.',
                'estimated_lakh' => 495.00,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 445.50, 'util_ss' => 49.50, 'util_tot' => 495.00,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-17',
                'division' => 'Silchar',
                'name' => 'A/E measures at Choudhurighat area of Silchar town on L/B of river Barak.',
                'estimated_lakh' => 588.16,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 529.34, 'util_ss' => 58.86, 'util_tot' => 588.20,
                'req_cs' => 0.00, 'req_ss' => 0.00, 'req_tot' => 0.00,
            ],
            [
                'code' => 'AS-18',
                'division' => 'CID, Badarpur',
                'name' => 'Anti erosion measures to protect Barak dyke from Ganirgram to Katigorah on its R/B (Ch 0-700 m) at Sealtek.',
                'estimated_lakh' => 680.83,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 486.40, 'util_ss' => 162.10, 'util_tot' => 648.50,
                'req_cs' => 32.33, 'req_ss' => 0.00, 'req_tot' => 32.33,
            ],
            [
                'code' => 'AS-19',
                'division' => 'CID, Badarpur',
                'name' => 'Extension of existing protection works at Gobindapur, Siddipur and Balirband area from erosion of river Barak on its R/B (Ch 0 m to 400m) u/s and 0 m to 200 m d/s.',
                'estimated_lakh' => 596.00,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 464.04, 'util_ss' => 100.28, 'util_tot' => 564.32,
                'req_cs' => 31.68, 'req_ss' => 0.00, 'req_tot' => 31.68,
            ],
            [
                'code' => 'AS-20',
                'division' => 'Hailakandi',
                'name' => 'Protection of Kalinagar area from the erosion of river Barak on its L/B (Ch 0 m to 700 m).',
                'estimated_lakh' => 686.67,
                'status' => 'Completed',
                'progress' => 100.00,
                'util_cs' => 570.65, 'util_ss' => 78.16, 'util_tot' => 648.81,
                'req_cs' => 27.74, 'req_ss' => 0.00, 'req_tot' => 27.74,
            ],
        ];

        foreach ($data as $row) {
            $sanctionedCr = round($row['estimated_lakh'] / 100, 2);

            Scheme::updateOrCreate(
                ['scheme_code' => $row['code']],
                [
                    'scheme_name'              => $row['name'],
                    'division'                 => $row['division'],
                    'district'                 => $row['division'],
                    'river_basin'              => 'Brahmaputra',
                    'state'                    => 'Assam',
                    'plan_period'              => 'XI Plan',
                    'estimated_cost_lakh'      => $row['estimated_lakh'],
                    'sanctioned_amount_cr'     => $sanctionedCr,
                    'fund_utilised_cs_lakh'    => $row['util_cs'],
                    'fund_utilised_ss_lakh'    => $row['util_ss'],
                    'fund_utilised_total_lakh' => $row['util_tot'],
                    'fund_req_cs_lakh'         => $row['req_cs'],
                    'fund_req_ss_lakh'         => $row['req_ss'],
                    'fund_req_total_lakh'      => $row['req_tot'],
                    'central_share_pct'        => 90,
                    'state_share_pct'          => 10,
                    'project_type'             => 'Flood Management',
                    'physical_status'          => $row['status'],
                    'physical_progress_pct'    => $row['progress'],
                    'is_active'                => true,
                ]
            );
        }
    }
}
